# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-27 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u7535\u5f71\u540d')),
                ('rating', models.FloatField(default=0, verbose_name='\u8bc4\u5206')),
                ('poster_url_big', models.URLField(default='', verbose_name='\u7535\u5f71\u5c01\u9762-\u5927')),
                ('poster_url_me', models.URLField(default='', verbose_name='\u7535\u5f71\u5c01\u9762-\u4e2d')),
                ('directors', models.CharField(max_length=255, verbose_name='\u5bfc\u6f14')),
                ('casts', models.CharField(max_length=255, verbose_name='\u6f14\u5458')),
                ('created_time', models.DateTimeField(default=False, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('is_top', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8bc4\u5206\u6700\u9ad8')),
                ('is_in_theater', models.BooleanField(default=False, verbose_name='\u6b63\u5728\u4e0a\u6620')),
            ],
        ),
    ]
